#################################################################################
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    environment:
      IMAGE_NAME: "dockercraze/do-kubernetes-sample-app"
    working_directory: ~/app
    steps:
      # retrieve the code from GitHub
      - checkout
      # set up a remote, isolated environment for each build
      # this is required before using any docker command inside a job step
      # as those steps really need to be run on another machine
      - setup_remote_docker
      # first run step builds the image, used to be done locally when manual
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      # last run step pushes the image to DockerHub, possible now that the
      # login authentication is made possible using the environment variables set earlier
      # in the circleci project settings
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            # circle_sha1 is a special circleCI default variable, contains the hash of the commit
            # that it is building. Used here to ensure a new unique specific image
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_SHA1
            # next, edit kube/do-sample-deployment.yml
            # which needs to point to the same image sing this circleci variable
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.4/bin/linux/amd64/kubectl
            chmod u+x ./kubectl
      - run:
          name: Deploy Code
          command: ./scripts/ci-deploy.sh
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
#################################################################################
